// <auto-generated />
using System;
using CustomersAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomersAPI.Migrations
{
    [DbContext(typeof(CustomerDBContext))]
    [Migration("20230414084438_AddedSeedForUserCredentials")]
    partial class AddedSeedForUserCredentials
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CustomersAPI.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CityAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("256596bc-a8ab-488f-ad6e-2c8e12d3b3f4"),
                            AccessFailedCount = 0,
                            CityAddress = "Makati",
                            ConcurrencyStamp = "18d53e92-210d-436d-8921-fa5e35e06582",
                            DOB = new DateTime(2023, 4, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "su@crms.com",
                            EmailConfirmed = true,
                            FirstName = "Super",
                            LastName = "User",
                            LockoutEnabled = true,
                            NormalizedEmail = "SU@CRMS.COM",
                            NormalizedUserName = "SU@CRMS.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEDMD8OLE7DZds65sKRD4XGiLJAVWcqvdVXGWd9coPLfBmFN6Aa0AaQRUkAQ4Xmf+bQ==",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "su@crms.com"
                        },
                        new
                        {
                            Id = new Guid("db63ca1a-5162-4c55-9bf4-db8f8f462faa"),
                            AccessFailedCount = 0,
                            CityAddress = "Makati",
                            ConcurrencyStamp = "2b640e04-fb67-4b5b-96b6-c1db598dece4",
                            DOB = new DateTime(2023, 4, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "user@crms.com",
                            EmailConfirmed = true,
                            FirstName = "Regular",
                            LastName = "User",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER@CRMS.COM",
                            NormalizedUserName = "USER@CRMS.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEGU5ESXZ0PvHtphbItDPzTA+/FE+2tEGOGzdlQec7f1er5pqO79s3YaaRETGYcKiIA==",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "user@crms.com"
                        });
                });

            modelBuilder.Entity("CustomersAPI.Models.Customer", b =>
                {
                    b.Property<Guid>("Customer_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("RegularExpression", "^(09|\\+639)\\d{9}$");

                    b.HasKey("Customer_Id");

                    b.ToTable("CUSTOMERS LIST", (string)null);

                    b.HasData(
                        new
                        {
                            Customer_Id = new Guid("33e2c415-5514-4222-aff2-01343d995b21"),
                            Address = "5234 Crossing Street",
                            DOB = new DateTime(1975, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mauris.sagittis@icloud.edu",
                            FirstName = "Madeline",
                            Gender = "Female",
                            LastName = "Baxter",
                            Phone = "09123546789"
                        },
                        new
                        {
                            Customer_Id = new Guid("73251835-3495-4a7a-bdd0-9a3914649194"),
                            Address = "3 Pepper Wood Center",
                            DOB = new DateTime(1984, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "aabrahamovitz0@marketwatch.com",
                            FirstName = "Agatha",
                            Gender = "Female",
                            LastName = "Abrahamovitz",
                            Phone = "09601729545"
                        },
                        new
                        {
                            Customer_Id = new Guid("da34dca6-fe09-421f-b657-86f5ca3b3ece"),
                            Address = "97649 Corry Terrace",
                            DOB = new DateTime(1956, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mhabercham1@squidoo.com",
                            FirstName = "Maia",
                            Gender = "Female",
                            LastName = "Habercham",
                            Phone = "09184621695"
                        },
                        new
                        {
                            Customer_Id = new Guid("ceca175f-57d5-403f-908a-6c5153f96bd8"),
                            Address = "4608 Raven Parkway",
                            DOB = new DateTime(1987, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "amacrow2@globo.com",
                            FirstName = "Alane",
                            Gender = "Female",
                            LastName = "Macrow",
                            Phone = "09276939145"
                        },
                        new
                        {
                            Customer_Id = new Guid("d6238a76-b435-407f-b761-7713586fb829"),
                            Address = "2067 Golden Leaf Circle",
                            DOB = new DateTime(1964, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tedington3@illinois.edu",
                            FirstName = "Tracy",
                            Gender = "Male",
                            LastName = "Edington",
                            Phone = "09265235080"
                        },
                        new
                        {
                            Customer_Id = new Guid("be1926ac-858e-42f6-bb40-f627ea382f29"),
                            Address = "52014 Leroy Hill",
                            DOB = new DateTime(1954, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hsimunek4@yellowpages.com",
                            FirstName = "Hinze",
                            Gender = "Male",
                            LastName = "Simunek",
                            Phone = "09267006937"
                        },
                        new
                        {
                            Customer_Id = new Guid("a31a9831-f4e6-40db-9dc2-f5c9942acfc9"),
                            Address = "673 Autumn Leaf Court",
                            DOB = new DateTime(2006, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "asummerskill5@gravatar.com",
                            FirstName = "Angela",
                            Gender = "Female",
                            LastName = "Summerskill",
                            Phone = "09337435073"
                        },
                        new
                        {
                            Customer_Id = new Guid("da431e28-5e23-4086-836d-b8cbd9b9b7ae"),
                            Address = "9 Pleasure Way",
                            DOB = new DateTime(1978, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jbrowett6@mediafire.com",
                            FirstName = "Jed",
                            Gender = "Male",
                            LastName = "Browett",
                            Phone = "09143498357"
                        },
                        new
                        {
                            Customer_Id = new Guid("99dac0a4-a7cf-4f7b-bd7e-36f699e89b39"),
                            Address = "17 Columbus Junction",
                            DOB = new DateTime(1955, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "gbilson7@prnewswire.com",
                            FirstName = "Georgianna",
                            Gender = "Female",
                            LastName = "Bilson",
                            Phone = "09397882449"
                        },
                        new
                        {
                            Customer_Id = new Guid("2dbec5ac-bfd6-4587-a2cb-5126dbdffdbb"),
                            Address = "82368 Boyd Point",
                            DOB = new DateTime(2002, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahave8@so-net.ne.jp",
                            FirstName = "Alister",
                            Gender = "Male",
                            LastName = "Have",
                            Phone = "09638397843"
                        },
                        new
                        {
                            Customer_Id = new Guid("02df0ff1-b4bf-453f-85d2-e4b99029a6f2"),
                            Address = "59830 Brickson Park Road",
                            DOB = new DateTime(2001, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "khadlington9@paypal.com",
                            FirstName = "Kerianne",
                            Gender = "Female",
                            LastName = "Hadlington",
                            Phone = "09225056729"
                        },
                        new
                        {
                            Customer_Id = new Guid("fcc95f15-8f73-46b2-a31f-29d734d60309"),
                            Address = "624 Buhler Point",
                            DOB = new DateTime(1994, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mcrummaya@tripod.com",
                            FirstName = "Meggy",
                            Gender = "Female",
                            LastName = "Crummay",
                            Phone = "09392511444"
                        },
                        new
                        {
                            Customer_Id = new Guid("8e65c104-567d-46cd-8e86-f0dbee293880"),
                            Address = "64071 Acker Park",
                            DOB = new DateTime(1997, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cakramb@wsj.com",
                            FirstName = "Catlin",
                            Gender = "Female",
                            LastName = "Akram",
                            Phone = "09093870858"
                        },
                        new
                        {
                            Customer_Id = new Guid("2e16f60e-15ec-484a-8a8c-382428be38a4"),
                            Address = "58172 Ruskin Crossing",
                            DOB = new DateTime(1965, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tcantoc@msu.edu",
                            FirstName = "Trenton",
                            Gender = "Male",
                            LastName = "Canto",
                            Phone = "09809339189"
                        },
                        new
                        {
                            Customer_Id = new Guid("8f42744d-ff97-4f7f-8da8-6ac5287e9fa3"),
                            Address = "1 Pond Center",
                            DOB = new DateTime(1996, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mmularkeyd@typepad.com",
                            FirstName = "Montague",
                            Gender = "Male",
                            LastName = "Mularkey",
                            Phone = "09306995169"
                        },
                        new
                        {
                            Customer_Id = new Guid("425228a9-302d-4b51-8244-9c3ca1bf0d17"),
                            Address = "4526 Northfield Road",
                            DOB = new DateTime(1953, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mmerryfielde@nih.gov",
                            FirstName = "Morganica",
                            Gender = "Female",
                            LastName = "Merryfield",
                            Phone = "09003901945"
                        },
                        new
                        {
                            Customer_Id = new Guid("c1e5e2b3-bd3f-43ce-b3c7-9ecffe0d857d"),
                            Address = "03722 Westridge Court",
                            DOB = new DateTime(1997, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cthomkinsf@etsy.com",
                            FirstName = "Con",
                            Gender = "Female",
                            LastName = "Thomkins",
                            Phone = "09939955254"
                        },
                        new
                        {
                            Customer_Id = new Guid("5eadd148-261e-46f5-a2d3-1155444118b5"),
                            Address = "62956 1st Street",
                            DOB = new DateTime(1972, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rmorgang@bbc.co.uk",
                            FirstName = "Rudy",
                            Gender = "Male",
                            LastName = "Morgan",
                            Phone = "09597429865"
                        },
                        new
                        {
                            Customer_Id = new Guid("8a0e89b3-3456-463d-832c-2c992f781a7d"),
                            Address = "57 Hagan Point",
                            DOB = new DateTime(1992, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rskedgeh@google.de",
                            FirstName = "Rhianna",
                            Gender = "Female",
                            LastName = "Skedge",
                            Phone = "09956873369"
                        },
                        new
                        {
                            Customer_Id = new Guid("21ead0ef-3293-4465-8155-c13d9f0c9faf"),
                            Address = "9664 Redwing Court",
                            DOB = new DateTime(1991, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fstoweri@engadget.com",
                            FirstName = "Farlee",
                            Gender = "Male",
                            LastName = "Stower",
                            Phone = "09579026072"
                        },
                        new
                        {
                            Customer_Id = new Guid("4e55d116-b5b3-49b8-93c5-1e4fa36f5ba2"),
                            Address = "1 Dawn Circle",
                            DOB = new DateTime(1994, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ddimnagej@etsy.com",
                            FirstName = "Delano",
                            Gender = "Male",
                            LastName = "Dimnage",
                            Phone = "09662401440"
                        });
                });

            modelBuilder.Entity("CustomersAPI.Models.Transactions", b =>
                {
                    b.Property<Guid>("Transaction_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("TransactionDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.HasKey("Transaction_Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("TRANSACTIONS LIST", (string)null);

                    b.HasData(
                        new
                        {
                            Transaction_Id = new Guid("3630dd88-6912-40a1-9d88-26dc54a9e449"),
                            Amount = 6068.91m,
                            CustomerId = new Guid("425228a9-302d-4b51-8244-9c3ca1bf0d17"),
                            TransactionDate = new DateTime(2022, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("fb238fa9-8f3e-45d8-9b59-d407d0e6f674"),
                            Amount = 6523.52m,
                            CustomerId = new Guid("425228a9-302d-4b51-8244-9c3ca1bf0d17"),
                            TransactionDate = new DateTime(2022, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("ae909e7c-5b9c-4ccf-81b4-31dfc403846f"),
                            Amount = 16861.07m,
                            CustomerId = new Guid("4e55d116-b5b3-49b8-93c5-1e4fa36f5ba2"),
                            TransactionDate = new DateTime(2022, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("6c4ca165-1a03-43da-a4cf-3509b5b0eae1"),
                            Amount = 15743.60m,
                            CustomerId = new Guid("be1926ac-858e-42f6-bb40-f627ea382f29"),
                            TransactionDate = new DateTime(2022, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("50c6dbbc-3713-4109-82ca-4c7eae551bfd"),
                            Amount = 3896.77m,
                            CustomerId = new Guid("ceca175f-57d5-403f-908a-6c5153f96bd8"),
                            TransactionDate = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("a22b8c3a-fd85-4f1e-8e4a-c82af373b9f9"),
                            Amount = 14115.62m,
                            CustomerId = new Guid("5eadd148-261e-46f5-a2d3-1155444118b5"),
                            TransactionDate = new DateTime(2022, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("3ea082f2-cd6f-4f42-a127-e07188d8fc31"),
                            Amount = 1347.45m,
                            CustomerId = new Guid("21ead0ef-3293-4465-8155-c13d9f0c9faf"),
                            TransactionDate = new DateTime(2022, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("2c5b5687-54e2-45b1-901a-c38235fc2fb8"),
                            Amount = 19644.39m,
                            CustomerId = new Guid("5eadd148-261e-46f5-a2d3-1155444118b5"),
                            TransactionDate = new DateTime(2022, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("e3d6b451-ef57-4b38-a9f8-988eb638d726"),
                            Amount = 14420.64m,
                            CustomerId = new Guid("da431e28-5e23-4086-836d-b8cbd9b9b7ae"),
                            TransactionDate = new DateTime(2022, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("fe2af285-4452-4194-b9e9-fe5991a8d460"),
                            Amount = 13405.27m,
                            CustomerId = new Guid("d6238a76-b435-407f-b761-7713586fb829"),
                            TransactionDate = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("01048b1d-1750-45bd-b383-b61138366509"),
                            Amount = 14215.58m,
                            CustomerId = new Guid("a31a9831-f4e6-40db-9dc2-f5c9942acfc9"),
                            TransactionDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("6a23863b-24de-437b-975f-fd48a117d0f4"),
                            Amount = 17181.86m,
                            CustomerId = new Guid("4e55d116-b5b3-49b8-93c5-1e4fa36f5ba2"),
                            TransactionDate = new DateTime(2022, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("fc6c35e2-5ecc-4e50-b17f-005431821c58"),
                            Amount = 12838.18m,
                            CustomerId = new Guid("8f42744d-ff97-4f7f-8da8-6ac5287e9fa3"),
                            TransactionDate = new DateTime(2022, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("ad6f4565-70bf-431b-b3ba-c0b0eb2f3c9c"),
                            Amount = 3399.04m,
                            CustomerId = new Guid("2e16f60e-15ec-484a-8a8c-382428be38a4"),
                            TransactionDate = new DateTime(2023, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("fb5a014a-d9cb-4456-8734-e3bc90a83a04"),
                            Amount = 19017.30m,
                            CustomerId = new Guid("73251835-3495-4a7a-bdd0-9a3914649194"),
                            TransactionDate = new DateTime(2022, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("7001b639-bd3a-4c60-82ba-91dafaca5cad"),
                            Amount = 12621.27m,
                            CustomerId = new Guid("fcc95f15-8f73-46b2-a31f-29d734d60309"),
                            TransactionDate = new DateTime(2022, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("a4f60cc5-b9c7-434e-99a3-4deda04d0581"),
                            Amount = 8205.19m,
                            CustomerId = new Guid("da431e28-5e23-4086-836d-b8cbd9b9b7ae"),
                            TransactionDate = new DateTime(2022, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("b6b17cee-c700-4661-909b-f49b71966ead"),
                            Amount = 18900.31m,
                            CustomerId = new Guid("c1e5e2b3-bd3f-43ce-b3c7-9ecffe0d857d"),
                            TransactionDate = new DateTime(2022, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("4d01f758-8356-4087-a6c7-0cc1e070446e"),
                            Amount = 19958.59m,
                            CustomerId = new Guid("4e55d116-b5b3-49b8-93c5-1e4fa36f5ba2"),
                            TransactionDate = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("4c421b63-d2cb-4ef3-8187-e11149b24d5f"),
                            Amount = 13524.20m,
                            CustomerId = new Guid("4e55d116-b5b3-49b8-93c5-1e4fa36f5ba2"),
                            TransactionDate = new DateTime(2022, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("6bc44dc4-38c3-406d-9d8d-a4aef4093272"),
                            Amount = 7914.91m,
                            CustomerId = new Guid("21ead0ef-3293-4465-8155-c13d9f0c9faf"),
                            TransactionDate = new DateTime(2022, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("4eedb424-5495-42f0-ad53-4a3fe7a1503f"),
                            Amount = 14447.04m,
                            CustomerId = new Guid("2dbec5ac-bfd6-4587-a2cb-5126dbdffdbb"),
                            TransactionDate = new DateTime(2022, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("f9ed77f3-ac7b-4b18-a60a-bcaa6beb6032"),
                            Amount = 4079.20m,
                            CustomerId = new Guid("2e16f60e-15ec-484a-8a8c-382428be38a4"),
                            TransactionDate = new DateTime(2022, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("370e4062-1e57-45d7-b5e5-2c8b9498125c"),
                            Amount = 17809.47m,
                            CustomerId = new Guid("8a0e89b3-3456-463d-832c-2c992f781a7d"),
                            TransactionDate = new DateTime(2023, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("4c2e3da6-5623-4a8c-8b2d-e34311c7cb47"),
                            Amount = 12163.93m,
                            CustomerId = new Guid("d6238a76-b435-407f-b761-7713586fb829"),
                            TransactionDate = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("0e16da4a-aece-4133-9c1c-129c7e388792"),
                            Amount = 10839.38m,
                            CustomerId = new Guid("99dac0a4-a7cf-4f7b-bd7e-36f699e89b39"),
                            TransactionDate = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("1b940fe1-c921-41d0-aa10-67171f4656f4"),
                            Amount = 17362.33m,
                            CustomerId = new Guid("ceca175f-57d5-403f-908a-6c5153f96bd8"),
                            TransactionDate = new DateTime(2022, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("29c929de-7280-40c7-a49e-a3762d21e0a1"),
                            Amount = 15326.44m,
                            CustomerId = new Guid("da431e28-5e23-4086-836d-b8cbd9b9b7ae"),
                            TransactionDate = new DateTime(2023, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("f6897448-5f0d-41ee-8eae-70b5979a33e9"),
                            Amount = 15225.41m,
                            CustomerId = new Guid("2dbec5ac-bfd6-4587-a2cb-5126dbdffdbb"),
                            TransactionDate = new DateTime(2023, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("9cf6afd4-e40c-46f6-a67b-bc651e9e9b89"),
                            Amount = 8243.38m,
                            CustomerId = new Guid("da34dca6-fe09-421f-b657-86f5ca3b3ece"),
                            TransactionDate = new DateTime(2023, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("372e35cb-0781-43de-b768-fc5e91f1ad07"),
                            Amount = 19646.52m,
                            CustomerId = new Guid("c1e5e2b3-bd3f-43ce-b3c7-9ecffe0d857d"),
                            TransactionDate = new DateTime(2022, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("3ca8d891-0969-4efe-adeb-e5b598083c14"),
                            Amount = 5587.62m,
                            CustomerId = new Guid("8a0e89b3-3456-463d-832c-2c992f781a7d"),
                            TransactionDate = new DateTime(2023, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("c6892c50-1f91-4cf1-b18e-15166c57c294"),
                            Amount = 8628.20m,
                            CustomerId = new Guid("425228a9-302d-4b51-8244-9c3ca1bf0d17"),
                            TransactionDate = new DateTime(2023, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("d8d5a4fa-14a6-4c47-a466-263dd29cde6b"),
                            Amount = 3134.06m,
                            CustomerId = new Guid("2dbec5ac-bfd6-4587-a2cb-5126dbdffdbb"),
                            TransactionDate = new DateTime(2022, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("b03efc9c-0b0e-4581-8198-0a0e3f508069"),
                            Amount = 7895.30m,
                            CustomerId = new Guid("8f42744d-ff97-4f7f-8da8-6ac5287e9fa3"),
                            TransactionDate = new DateTime(2022, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("ff31add8-49c5-4572-9329-4deed784ba98"),
                            Amount = 2116.34m,
                            CustomerId = new Guid("425228a9-302d-4b51-8244-9c3ca1bf0d17"),
                            TransactionDate = new DateTime(2022, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("79b840a2-9a80-41ae-82ee-43c2a78ac705"),
                            Amount = 14523.92m,
                            CustomerId = new Guid("da34dca6-fe09-421f-b657-86f5ca3b3ece"),
                            TransactionDate = new DateTime(2022, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("68337dfd-8c0f-4812-ade2-aaf351f25d60"),
                            Amount = 15192.52m,
                            CustomerId = new Guid("2e16f60e-15ec-484a-8a8c-382428be38a4"),
                            TransactionDate = new DateTime(2023, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("b5540009-e2e9-4138-81b5-df1712948c4d"),
                            Amount = 11703.50m,
                            CustomerId = new Guid("be1926ac-858e-42f6-bb40-f627ea382f29"),
                            TransactionDate = new DateTime(2022, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("1d918d3a-d9ee-4817-ad10-61cb7b52d359"),
                            Amount = 9842.85m,
                            CustomerId = new Guid("21ead0ef-3293-4465-8155-c13d9f0c9faf"),
                            TransactionDate = new DateTime(2022, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("db5e5d48-e1c9-4022-b6fa-3acdd87d479c"),
                            Amount = 3940.43m,
                            CustomerId = new Guid("8a0e89b3-3456-463d-832c-2c992f781a7d"),
                            TransactionDate = new DateTime(2022, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("57474223-7c09-4889-99ae-378d48191238"),
                            Amount = 13910.67m,
                            CustomerId = new Guid("99dac0a4-a7cf-4f7b-bd7e-36f699e89b39"),
                            TransactionDate = new DateTime(2022, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("e3d43e04-f4d6-435d-b79e-683051ee5b96"),
                            Amount = 1183.59m,
                            CustomerId = new Guid("8e65c104-567d-46cd-8e86-f0dbee293880"),
                            TransactionDate = new DateTime(2022, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("97fb9568-67ea-4cc6-8e0a-d80dee10055b"),
                            Amount = 12396.27m,
                            CustomerId = new Guid("ceca175f-57d5-403f-908a-6c5153f96bd8"),
                            TransactionDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("171103cc-47d0-4b2f-b313-d748d03d9166"),
                            Amount = 18095.37m,
                            CustomerId = new Guid("8e65c104-567d-46cd-8e86-f0dbee293880"),
                            TransactionDate = new DateTime(2022, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("479adc5a-9ec3-4f98-bc42-96be94e84d52"),
                            Amount = 7388.27m,
                            CustomerId = new Guid("8f42744d-ff97-4f7f-8da8-6ac5287e9fa3"),
                            TransactionDate = new DateTime(2022, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("587c6c5b-530c-41d2-b54a-97a50529b119"),
                            Amount = 5204.34m,
                            CustomerId = new Guid("425228a9-302d-4b51-8244-9c3ca1bf0d17"),
                            TransactionDate = new DateTime(2022, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("59ce3242-d8ee-4465-af89-d4a6ba0eeb82"),
                            Amount = 14562.70m,
                            CustomerId = new Guid("4e55d116-b5b3-49b8-93c5-1e4fa36f5ba2"),
                            TransactionDate = new DateTime(2023, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("fdddf646-72f2-4c6a-ba90-2e2db37a9b3b"),
                            Amount = 12432.71m,
                            CustomerId = new Guid("8e65c104-567d-46cd-8e86-f0dbee293880"),
                            TransactionDate = new DateTime(2023, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Transaction_Id = new Guid("cdbe5de4-0d84-4bba-ad3d-4f59ab09cbab"),
                            Amount = 9929.75m,
                            CustomerId = new Guid("5eadd148-261e-46f5-a2d3-1155444118b5"),
                            TransactionDate = new DateTime(2022, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CustomersAPI.Models.Transactions", b =>
                {
                    b.HasOne("CustomersAPI.Models.Customer", "Customer")
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Customer_ID");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CustomersAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CustomersAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomersAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CustomersAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CustomersAPI.Models.Customer", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
