// <auto-generated />
using System;
using CRMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRMS.Migrations
{
    [DbContext(typeof(CRMSDbContext))]
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
    [Migration("20230423200040_initDBSchema042423")]
    partial class initDBSchema042423
========
    [Migration("20230423093856_init")]
    partial class init
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CRMS.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CityAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("isHidden")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            Id = new Guid("e4274999-2c7e-4cc0-8a65-2381570c01c6"),
                            AccessFailedCount = 0,
                            CityAddress = "Makati",
                            ConcurrencyStamp = "791f1789-7c0d-4a3e-ae38-1a877ecef31d",
                            DOB = new DateTime(2023, 4, 24, 0, 0, 0, 0, DateTimeKind.Local),
========
                            Id = new Guid("f9f3b8b2-26eb-4731-8680-323863682bde"),
                            AccessFailedCount = 0,
                            CityAddress = "Makati",
                            ConcurrencyStamp = "e7b207a8-3c04-48f8-b31d-5f82c262128f",
                            DOB = new DateTime(2023, 4, 23, 0, 0, 0, 0, DateTimeKind.Local),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            Email = "su@crms.com",
                            EmailConfirmed = true,
                            FirstName = "System",
                            LastName = "Admin",
                            LockoutEnabled = true,
                            NormalizedEmail = "SU@CRMS.COM",
                            NormalizedUserName = "SYSADMIN",
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            PasswordHash = "AQAAAAEAACcQAAAAEGr2hZWmn+8mxAbr95+sUKDoB86KaJDY1Of0AuHb1Puelw8Cgq3CgFiw5BzqM9VZoA==",
========
                            PasswordHash = "AQAAAAEAACcQAAAAENybnSXDKyQK0XlvbmAUhZuAy5KQWEbGd93myO/Avbc8vdqNY8cKY8qPJ1YRX2fbHQ==",
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "SysAdmin",
                            isHidden = true
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            Id = new Guid("ad5f6c61-63ef-4be2-a9fa-7376f3f0f828"),
                            AccessFailedCount = 0,
                            CityAddress = "Pasay",
                            ConcurrencyStamp = "db6e4909-2159-451a-b3d3-bbb840307081",
                            DOB = new DateTime(2023, 4, 24, 0, 0, 0, 0, DateTimeKind.Local),
========
                            Id = new Guid("6647c921-35f0-4980-b014-e8e9b50c4066"),
                            AccessFailedCount = 0,
                            CityAddress = "Pasay",
                            ConcurrencyStamp = "11637642-2144-4c8a-8e3b-347670703621",
                            DOB = new DateTime(2023, 4, 23, 0, 0, 0, 0, DateTimeKind.Local),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            Email = "cgl@crms.com",
                            EmailConfirmed = true,
                            FirstName = "Charl",
                            LastName = "Legista",
                            LockoutEnabled = true,
                            NormalizedEmail = "CGL@CRMS.COM",
                            NormalizedUserName = "CGL@CRMS.COM",
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            PasswordHash = "AQAAAAEAACcQAAAAEIn4zwscNkGVNJLeMPeXmjeRViNT1XN3FT4VJJMpILjM/NbTjS6z+NSYDUqx5u889A==",
========
                            PasswordHash = "AQAAAAEAACcQAAAAEC+8pJIlltmWyIVFNwLshLYslABmM5y8/Wm5t2oRCCojLNA5SeJin2aZKzDp+mJpaQ==",
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "cgl@crms.com",
                            isHidden = false
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            Id = new Guid("1d20c7d3-d246-4fc2-9b15-75e4b5769074"),
                            AccessFailedCount = 0,
                            CityAddress = "General Trias",
                            ConcurrencyStamp = "90be228b-4d46-466e-b357-a79e51b89a75",
                            DOB = new DateTime(2023, 4, 24, 0, 0, 0, 0, DateTimeKind.Local),
========
                            Id = new Guid("24121e19-d6a8-4a31-868a-35810c07a6b9"),
                            AccessFailedCount = 0,
                            CityAddress = "General Trias",
                            ConcurrencyStamp = "b28050f8-37c0-4766-af38-22f1f7c3bdbd",
                            DOB = new DateTime(2023, 4, 23, 0, 0, 0, 0, DateTimeKind.Local),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            Email = "sbb@crms.com",
                            EmailConfirmed = true,
                            FirstName = "Steven",
                            LastName = "Baris",
                            LockoutEnabled = true,
                            NormalizedEmail = "SBB@CRMS.COM",
                            NormalizedUserName = "SBB@CRMS.COM",
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            PasswordHash = "AQAAAAEAACcQAAAAEDEBeac4uRZjCvAteS6mE0l/A7JKr+OanqF0ppOUORXUmMeuMxhpP2JfJ86nzyIDSw==",
========
                            PasswordHash = "AQAAAAEAACcQAAAAELf+Af5kohSklNp8FFWVBtUhp9E6I38dbormytOCml4dzJJ55rv6eFXjN6cYd4O+vA==",
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "sbb@crms.com",
                            isHidden = false
                        });
                });

            modelBuilder.Entity("CRMS.Models.Contacts", b =>
                {
                    b.Property<Guid>("Contact_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContactCreatorID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContactOwnerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DOB")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateAssigned")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsLocal")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Contact_Id");

                    b.HasIndex("ContactCreatorID");

                    b.HasIndex("ContactOwnerID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.ToTable("CONTACTS", (string)null);
                });

            modelBuilder.Entity("CRMS.Models.Customization.AppointmentPurpose", b =>
                {
                    b.Property<Guid>("Purpose_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PurposeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Purpose_Id");

                    b.ToTable("APPOINTMENT_PURPOSES", (string)null);

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            Purpose_Id = new Guid("499871d7-1bc7-4102-857e-8972755c1a1c"),
========
                            Purpose_Id = new Guid("17618a75-4ccd-4791-8031-69b263b8bd8b"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            PurposeName = "Fact-Find"
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            Purpose_Id = new Guid("727a1bc8-3a8f-4ee8-97d3-6a94531b2b83"),
========
                            Purpose_Id = new Guid("bbf31318-e6a5-433c-bea8-307c557d01fd"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            PurposeName = "Presentation"
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            Purpose_Id = new Guid("8ad436ec-a101-4bb8-a320-8cdd1d50a914"),
========
                            Purpose_Id = new Guid("4f318d3b-4b83-4e3c-9948-6167a933c13f"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            PurposeName = "Proposal"
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            Purpose_Id = new Guid("bffea4d7-9e98-4bb3-a48b-67225c55ecac"),
========
                            Purpose_Id = new Guid("695d0f03-c986-47b4-b30a-16c3ea5db64a"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            PurposeName = "Sales Closing"
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            Purpose_Id = new Guid("06ea6c17-714f-47ef-a50a-177bdea0934d"),
========
                            Purpose_Id = new Guid("d769d517-77c0-402b-b5d5-903c0d88737a"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            PurposeName = "Others"
                        });
                });

            modelBuilder.Entity("CRMS.Models.Customization.CommunicationMethod", b =>
                {
                    b.Property<Guid>("CommunicationMethod_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommunicationMethodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommunicationMethod_Id");

                    b.ToTable("ENGAGEMENT_COMMUNICATION METHODS", (string)null);

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            CommunicationMethod_Id = new Guid("bef323bd-63c3-4049-8d1b-c2ab220679a6"),
========
                            CommunicationMethod_Id = new Guid("eeb2b9b7-9c54-4442-ba5c-c97741fe5aa3"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            CommunicationMethodName = "Facebook"
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            CommunicationMethod_Id = new Guid("32b8e209-59f0-4a25-8a21-8a679760f2ac"),
========
                            CommunicationMethod_Id = new Guid("a419f484-6089-4da2-9b2d-d4c630e88a98"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            CommunicationMethodName = "Instagram"
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            CommunicationMethod_Id = new Guid("6b27026b-6394-4a31-ac3e-3f0e74c77a2d"),
========
                            CommunicationMethod_Id = new Guid("c1b22338-028f-41cf-b88b-b244def4c861"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            CommunicationMethodName = "WhatsApp"
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            CommunicationMethod_Id = new Guid("99e90010-0595-410a-aa15-8cf020ccbd20"),
========
                            CommunicationMethod_Id = new Guid("a095109a-ddb5-40fb-bd4b-5f829822f8cd"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            CommunicationMethodName = "Line"
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            CommunicationMethod_Id = new Guid("18357e57-c373-4f9c-ae33-76832c00104c"),
========
                            CommunicationMethod_Id = new Guid("f566f556-a05c-4dcd-905d-991a7150d16e"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            CommunicationMethodName = "Phone Call"
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            CommunicationMethod_Id = new Guid("a1514fe1-14b1-4dae-9611-5e89110135a2"),
                            CommunicationMethodName = "Text Message"
                        },
                        new
                        {
                            CommunicationMethod_Id = new Guid("214e8e5a-ac60-4e48-a67e-3dbbb40c5686"),
========
                            CommunicationMethod_Id = new Guid("72de5d06-2ab1-4988-9271-f93ba7e393a4"),
                            CommunicationMethodName = "Test Message"
                        },
                        new
                        {
                            CommunicationMethod_Id = new Guid("05b25a74-47d9-43ee-8ce8-625c28697866"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            CommunicationMethodName = "Email"
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            CommunicationMethod_Id = new Guid("af9cf827-ff7f-497a-8353-3344ff0b1bb7"),
========
                            CommunicationMethod_Id = new Guid("080b32e8-5665-4abe-91f5-dfccf8afe2c7"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            CommunicationMethodName = "Others"
                        });
                });

            modelBuilder.Entity("CRMS.Models.Customization.Effectivity", b =>
                {
                    b.Property<Guid>("Effectivity_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Effectivity_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Effectivity_Id");

                    b.ToTable("ENGAGEMENT_EFFECTIVITY", (string)null);

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            Effectivity_Id = new Guid("e23d60bb-7a4e-4d65-b187-f507e90dfab8"),
========
                            Effectivity_Id = new Guid("c47a6bbe-cacf-4994-9510-7256a39a00cd"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            Effectivity_Name = "Not Read"
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            Effectivity_Id = new Guid("9ec40974-f249-40ff-abe2-43bbe0746c25"),
========
                            Effectivity_Id = new Guid("dbc18a5c-684d-4725-adaf-c443489c9072"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            Effectivity_Name = "Read but no response"
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            Effectivity_Id = new Guid("aa0e640d-c539-4d85-8aa7-798807dbbea7"),
========
                            Effectivity_Id = new Guid("4798ec67-155d-4782-9777-d13584441693"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            Effectivity_Name = "Simple Response"
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            Effectivity_Id = new Guid("f468e49a-c029-4fca-a45f-f5bb71f78757"),
========
                            Effectivity_Id = new Guid("d3e83cb9-1dd3-4272-82a9-f4b815238b55"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            Effectivity_Name = "Good Engagement"
                        });
                });

            modelBuilder.Entity("CRMS.Models.Customization.EngagementType", b =>
                {
                    b.Property<Guid>("EType_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EngagementName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EType_Id");

                    b.ToTable("ENGAGEMENT_ENGAGEMENT-TYPES", (string)null);

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            EType_Id = new Guid("784c6bec-1b25-4d57-9a35-a2c8c2c5cc95"),
========
                            EType_Id = new Guid("c5a5a5ca-c0cf-49df-84d8-702cd0b81a75"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            EngagementName = "Congratulations"
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            EType_Id = new Guid("432fd84e-576a-49ec-936f-1f3dcd358a0c"),
========
                            EType_Id = new Guid("7c544101-6b83-4c11-93e6-7098440ef5b2"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            EngagementName = "Birthday"
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            EType_Id = new Guid("7c144eb1-e968-4a70-ae61-e6a40e892631"),
========
                            EType_Id = new Guid("0ed0bb6d-0696-4ba9-bad3-657d75807fa2"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            EngagementName = "Anniversary"
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            EType_Id = new Guid("749126c4-2d23-4c22-99cd-d903d670c9cb"),
========
                            EType_Id = new Guid("882974f5-85b8-4337-9ea8-47afa0fe9301"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            EngagementName = "Holiday"
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            EType_Id = new Guid("e8782cc4-9a0b-4313-acd4-d70a6314ed31"),
========
                            EType_Id = new Guid("12acb338-beb6-4b96-b501-e8d3be46b26b"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            EngagementName = "Discount"
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            EType_Id = new Guid("772282ba-5e65-4f65-97bd-b2745bd0d6c2"),
========
                            EType_Id = new Guid("2faebbed-05e4-4d93-b9d2-248e287200b8"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            EngagementName = "Company News"
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            EType_Id = new Guid("cefdbe49-bc17-4afb-87d5-3340c5f5b700"),
========
                            EType_Id = new Guid("90416b52-37af-4154-8e42-05f75a057e90"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            EngagementName = "New Product"
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            EType_Id = new Guid("1a43ad67-336e-4511-8411-0a133c84e0ce"),
========
                            EType_Id = new Guid("6d4961de-8a4f-4670-ae7f-889ebcfcbc91"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            EngagementName = "Others"
                        });
                });

            modelBuilder.Entity("CRMS.Models.Customization.LeadStatus", b =>
                {
                    b.Property<Guid>("LeadStatus_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LeadStatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeadStatus_Id");

                    b.ToTable("LEADS_STATUSES", (string)null);

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            LeadStatus_Id = new Guid("7a45fef7-675c-4946-834d-0d32bbabaf49"),
========
                            LeadStatus_Id = new Guid("0bdd51f6-8454-4275-bc8a-965b8ba35b70"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            LeadStatusName = "Contacted"
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            LeadStatus_Id = new Guid("6d0ec1f7-2cc2-4a01-af87-916495693238"),
========
                            LeadStatus_Id = new Guid("ea053f5d-7a33-431e-8b04-8b46fcb0e9cb"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            LeadStatusName = "Met"
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            LeadStatus_Id = new Guid("1271a7ed-bd75-4376-b472-221a614c4d40"),
========
                            LeadStatus_Id = new Guid("8ea3cf44-ac1c-49e9-86c9-3cde7b8a0a78"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            LeadStatusName = "Proposal Generated"
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            LeadStatus_Id = new Guid("65ea5bc2-716a-4f85-80cf-f29cde0de0aa"),
========
                            LeadStatus_Id = new Guid("8edeba47-db89-4d88-9ad1-327fb80fd9bb"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            LeadStatusName = "Application Submitted"
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            LeadStatus_Id = new Guid("b2458401-af60-4e14-8bfc-0f0f3db52799"),
========
                            LeadStatus_Id = new Guid("90f50456-afc4-4063-8a21-01f21b73e769"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            LeadStatusName = "Policy Issued"
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            LeadStatus_Id = new Guid("592b29b1-2afa-4004-98d0-ee4847d91825"),
========
                            LeadStatus_Id = new Guid("0533adba-60cc-4735-a300-769385d852e3"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            LeadStatusName = "Lead is Dead"
                        });
                });

            modelBuilder.Entity("CRMS.Models.Customization.Source", b =>
                {
                    b.Property<Guid>("Source_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Source_Id");

                    b.ToTable("LEADS_SOURCES", (string)null);

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            Source_Id = new Guid("77f583a7-8e34-4d23-a1ae-f73b5f31b2ab"),
========
                            Source_Id = new Guid("66a44d1f-eb08-4fba-98c2-c9e3e299a3f6"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            SourceName = "Referral"
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            Source_Id = new Guid("b915d906-52b0-4afc-a880-09e1e1f86e5e"),
========
                            Source_Id = new Guid("ef54390c-3cef-4863-a776-82d7427dc5e2"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            SourceName = "Friend"
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            Source_Id = new Guid("993f9d84-caf7-4730-add5-5f836cdb47e6"),
========
                            Source_Id = new Guid("1adac791-ae26-4254-87f2-413110bf70a9"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            SourceName = "Company-Generated"
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            Source_Id = new Guid("cfa5213c-78cb-4c9b-8d89-65448883a200"),
========
                            Source_Id = new Guid("766dad50-8192-4164-8e96-41a0fa3d96b6"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            SourceName = "Social Media"
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            Source_Id = new Guid("0b53fbe1-c7a3-4feb-8f81-960142e7a58c"),
========
                            Source_Id = new Guid("e21688b1-8b7b-4a00-a479-c7c74779684f"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            SourceName = "Webinar"
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            Source_Id = new Guid("23c5aafb-3cf8-491a-91f8-fec7f2699024"),
========
                            Source_Id = new Guid("b6263368-8d5c-4072-b378-eb5e71770dc3"),
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            SourceName = "Others"
                        });
                });

            modelBuilder.Entity("CRMS.Models.Product", b =>
                {
                    b.Property<Guid>("Product_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Benefits")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Product_Id");

                    b.ToTable("PRODUCTS", (string)null);
                });

            modelBuilder.Entity("CRMS.Models.Records.Appointments", b =>
                {
                    b.Property<Guid>("Appointment_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Appointment_DateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PurposeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SchedStatus")
                        .HasColumnType("int");

                    b.HasKey("Appointment_Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PurposeId");

                    b.ToTable("APPOINTMENTS", (string)null);
                });

            modelBuilder.Entity("CRMS.Models.Records.Engagement", b =>
                {
                    b.Property<Guid>("Engagement_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommsMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ETypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EffectivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Engagement_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Engagement_Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Engagement_Id");

                    b.HasIndex("CommsMethodId");

                    b.HasIndex("ContactId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ETypeId");

                    b.HasIndex("EffectivityId");

                    b.ToTable("ENGAGEMENTS", (string)null);
                });

            modelBuilder.Entity("CRMS.Models.Records.Leads", b =>
                {
                    b.Property<Guid>("Leads_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LeadSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Leads_DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PrefContactDay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrefContactMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrefContactTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProspectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Leads_Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("LeadSourceId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProspectId");

                    b.HasIndex("StatusId");

                    b.ToTable("LEADS", (string)null);
                });

            modelBuilder.Entity("CRMS.Models.RollingTransactions", b =>
                {
                    b.Property<Guid?>("RollingTransactions_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("TransacationTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RollingTransactions_ID");

                    b.HasIndex("ContactId")
                        .IsUnique()
                        .HasFilter("[ContactId] IS NOT NULL");

                    b.ToTable("ROLLING TRANSACTIONS", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            Id = new Guid("eab657c4-6689-4028-bbb4-a6896c08c0b0"),
                            ConcurrencyStamp = "f2f178fe-c1bf-4876-905b-cd27ab5f8fda",
========
                            Id = new Guid("fc397f0f-4f1c-4908-a164-6828401b83dd"),
                            ConcurrencyStamp = "7f075340-59e7-4bfb-9ec9-3673fc4cfe0b",
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            Id = new Guid("85990ed4-8dbf-42a2-8ab2-3c9021385646"),
                            ConcurrencyStamp = "a974f481-64ba-4c9b-ba4e-b71ecf18a976",
========
                            Id = new Guid("00cfb9ad-32f7-4fd6-b661-4cd41d87194d"),
                            ConcurrencyStamp = "44838ed8-7994-4f4f-ab69-2f2264a9e059",
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:CRMS/Migrations/20230423200040_initDBSchema042423.Designer.cs
                            UserId = new Guid("e4274999-2c7e-4cc0-8a65-2381570c01c6"),
                            RoleId = new Guid("eab657c4-6689-4028-bbb4-a6896c08c0b0")
========
                            UserId = new Guid("f9f3b8b2-26eb-4731-8680-323863682bde"),
                            RoleId = new Guid("fc397f0f-4f1c-4908-a164-6828401b83dd")
>>>>>>>> 7240e749e6afa22f4ee53fd1ae0d3ea67611fc48:CRMS/Migrations/20230423093856_init.Designer.cs
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CRMS.Models.Contacts", b =>
                {
                    b.HasOne("CRMS.Models.ApplicationUser", "Creator")
                        .WithMany()
                        .HasForeignKey("ContactCreatorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ContactCreator");

                    b.HasOne("CRMS.Models.ApplicationUser", "Owner")
                        .WithMany("Contacts")
                        .HasForeignKey("ContactOwnerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ContactOwner");

                    b.HasOne("CRMS.Models.ApplicationUser", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ContactUpdater");

                    b.Navigation("Creator");

                    b.Navigation("Owner");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("CRMS.Models.Records.Appointments", b =>
                {
                    b.HasOne("CRMS.Models.Contacts", "prospect")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AppointmentProspect");

                    b.HasOne("CRMS.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AppointmentCreator");

                    b.HasOne("CRMS.Models.Customization.AppointmentPurpose", "AppointmentPurpose")
                        .WithMany()
                        .HasForeignKey("PurposeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AppointmentPurpose");

                    b.Navigation("AppointmentPurpose");

                    b.Navigation("User");

                    b.Navigation("prospect");
                });

            modelBuilder.Entity("CRMS.Models.Records.Engagement", b =>
                {
                    b.HasOne("CRMS.Models.Customization.CommunicationMethod", "CommunicationMethod")
                        .WithMany()
                        .HasForeignKey("CommsMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CommunicationMethod");

                    b.HasOne("CRMS.Models.Contacts", "Contacts")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Contacts");

                    b.HasOne("CRMS.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Creator");

                    b.HasOne("CRMS.Models.Customization.EngagementType", "EngagementType")
                        .WithMany()
                        .HasForeignKey("ETypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EngagementType");

                    b.HasOne("CRMS.Models.Customization.Effectivity", "Effectivity")
                        .WithMany()
                        .HasForeignKey("EffectivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Effectivity");

                    b.Navigation("CommunicationMethod");

                    b.Navigation("Contacts");

                    b.Navigation("Effectivity");

                    b.Navigation("EngagementType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CRMS.Models.Records.Leads", b =>
                {
                    b.HasOne("CRMS.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LeadsCreator");

                    b.HasOne("CRMS.Models.Customization.Source", "source")
                        .WithMany()
                        .HasForeignKey("LeadSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LeadsSource");

                    b.HasOne("CRMS.Models.Product", "product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LeadsProduct");

                    b.HasOne("CRMS.Models.Contacts", "prospect")
                        .WithMany()
                        .HasForeignKey("ProspectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LeadsProspect");

                    b.HasOne("CRMS.Models.Customization.LeadStatus", "status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LeadsStatus");

                    b.Navigation("User");

                    b.Navigation("product");

                    b.Navigation("prospect");

                    b.Navigation("source");

                    b.Navigation("status");
                });

            modelBuilder.Entity("CRMS.Models.RollingTransactions", b =>
                {
                    b.HasOne("CRMS.Models.Contacts", "Contacts")
                        .WithOne("Transactions")
                        .HasForeignKey("CRMS.Models.RollingTransactions", "ContactId")
                        .HasConstraintName("FK_TransactionsOfContact");

                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CRMS.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CRMS.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRMS.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CRMS.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CRMS.Models.ApplicationUser", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("CRMS.Models.Contacts", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
